/* ====================================================================== *
 * Copyright (c) 2010-2016 ZFFramework
 * home page: http://ZFFramework.com
 * blog: http://zsaber.com
 * contact: master@zsaber.com (Chinese and English only)
 * Distributed under MIT license:
 *   https://github.com/ZFFramework/ZFFramework/blob/master/license/license.txt
 * ====================================================================== */
package com.ZFFramework.Android.NativeEnum.ZFUIKit;

public class ZFUIKeyCode {
    public static final int e_kUnknown = ZFUIKeyCode.native_e_kUnknown();
    private static native int native_e_kUnknown();

    public static final int e_kEsc = ZFUIKeyCode.native_e_kEsc();
    private static native int native_e_kEsc();
    public static final int e_kTab = ZFUIKeyCode.native_e_kTab();
    private static native int native_e_kTab();
    public static final int e_kBackspace = ZFUIKeyCode.native_e_kBackspace();
    private static native int native_e_kBackspace();
    public static final int e_kEnter = ZFUIKeyCode.native_e_kEnter();
    private static native int native_e_kEnter();
    public static final int e_kSpace = ZFUIKeyCode.native_e_kSpace();
    private static native int native_e_kSpace();
    public static final int e_kCapsLock = ZFUIKeyCode.native_e_kCapsLock();
    private static native int native_e_kCapsLock();
    public static final int e_kShift = ZFUIKeyCode.native_e_kShift();
    private static native int native_e_kShift();
    public static final int e_kCtrl = ZFUIKeyCode.native_e_kCtrl();
    private static native int native_e_kCtrl();
    public static final int e_kAlt = ZFUIKeyCode.native_e_kAlt();
    private static native int native_e_kAlt();
    public static final int e_kCommand = ZFUIKeyCode.native_e_kCommand();
    private static native int native_e_kCommand();
    public static final int e_kContextMenu = ZFUIKeyCode.native_e_kContextMenu();
    private static native int native_e_kContextMenu();

    public static final int e_kF1 = ZFUIKeyCode.native_e_kF1();
    private static native int native_e_kF1();
    public static final int e_kF2 = ZFUIKeyCode.native_e_kF2();
    private static native int native_e_kF2();
    public static final int e_kF3 = ZFUIKeyCode.native_e_kF3();
    private static native int native_e_kF3();
    public static final int e_kF4 = ZFUIKeyCode.native_e_kF4();
    private static native int native_e_kF4();
    public static final int e_kF5 = ZFUIKeyCode.native_e_kF5();
    private static native int native_e_kF5();
    public static final int e_kF6 = ZFUIKeyCode.native_e_kF6();
    private static native int native_e_kF6();
    public static final int e_kF7 = ZFUIKeyCode.native_e_kF7();
    private static native int native_e_kF7();
    public static final int e_kF8 = ZFUIKeyCode.native_e_kF8();
    private static native int native_e_kF8();
    public static final int e_kF9 = ZFUIKeyCode.native_e_kF9();
    private static native int native_e_kF9();
    public static final int e_kF10 = ZFUIKeyCode.native_e_kF10();
    private static native int native_e_kF10();
    public static final int e_kF11 = ZFUIKeyCode.native_e_kF11();
    private static native int native_e_kF11();
    public static final int e_kF12 = ZFUIKeyCode.native_e_kF12();
    private static native int native_e_kF12();

    public static final int e_k0 = ZFUIKeyCode.native_e_k0();
    private static native int native_e_k0();
    public static final int e_k1 = ZFUIKeyCode.native_e_k1();
    private static native int native_e_k1();
    public static final int e_k2 = ZFUIKeyCode.native_e_k2();
    private static native int native_e_k2();
    public static final int e_k3 = ZFUIKeyCode.native_e_k3();
    private static native int native_e_k3();
    public static final int e_k4 = ZFUIKeyCode.native_e_k4();
    private static native int native_e_k4();
    public static final int e_k5 = ZFUIKeyCode.native_e_k5();
    private static native int native_e_k5();
    public static final int e_k6 = ZFUIKeyCode.native_e_k6();
    private static native int native_e_k6();
    public static final int e_k7 = ZFUIKeyCode.native_e_k7();
    private static native int native_e_k7();
    public static final int e_k8 = ZFUIKeyCode.native_e_k8();
    private static native int native_e_k8();
    public static final int e_k9 = ZFUIKeyCode.native_e_k9();
    private static native int native_e_k9();

    public static final int e_kA = ZFUIKeyCode.native_e_kA();
    private static native int native_e_kA();
    public static final int e_kB = ZFUIKeyCode.native_e_kB();
    private static native int native_e_kB();
    public static final int e_kC = ZFUIKeyCode.native_e_kC();
    private static native int native_e_kC();
    public static final int e_kD = ZFUIKeyCode.native_e_kD();
    private static native int native_e_kD();
    public static final int e_kE = ZFUIKeyCode.native_e_kE();
    private static native int native_e_kE();
    public static final int e_kF = ZFUIKeyCode.native_e_kF();
    private static native int native_e_kF();
    public static final int e_kG = ZFUIKeyCode.native_e_kG();
    private static native int native_e_kG();
    public static final int e_kH = ZFUIKeyCode.native_e_kH();
    private static native int native_e_kH();
    public static final int e_kI = ZFUIKeyCode.native_e_kI();
    private static native int native_e_kI();
    public static final int e_kJ = ZFUIKeyCode.native_e_kJ();
    private static native int native_e_kJ();
    public static final int e_kK = ZFUIKeyCode.native_e_kK();
    private static native int native_e_kK();
    public static final int e_kL = ZFUIKeyCode.native_e_kL();
    private static native int native_e_kL();
    public static final int e_kM = ZFUIKeyCode.native_e_kM();
    private static native int native_e_kM();
    public static final int e_kN = ZFUIKeyCode.native_e_kN();
    private static native int native_e_kN();
    public static final int e_kO = ZFUIKeyCode.native_e_kO();
    private static native int native_e_kO();
    public static final int e_kP = ZFUIKeyCode.native_e_kP();
    private static native int native_e_kP();
    public static final int e_kQ = ZFUIKeyCode.native_e_kQ();
    private static native int native_e_kQ();
    public static final int e_kR = ZFUIKeyCode.native_e_kR();
    private static native int native_e_kR();
    public static final int e_kS = ZFUIKeyCode.native_e_kS();
    private static native int native_e_kS();
    public static final int e_kT = ZFUIKeyCode.native_e_kT();
    private static native int native_e_kT();
    public static final int e_kU = ZFUIKeyCode.native_e_kU();
    private static native int native_e_kU();
    public static final int e_kV = ZFUIKeyCode.native_e_kV();
    private static native int native_e_kV();
    public static final int e_kW = ZFUIKeyCode.native_e_kW();
    private static native int native_e_kW();
    public static final int e_kX = ZFUIKeyCode.native_e_kX();
    private static native int native_e_kX();
    public static final int e_kY = ZFUIKeyCode.native_e_kY();
    private static native int native_e_kY();
    public static final int e_kZ = ZFUIKeyCode.native_e_kZ();
    private static native int native_e_kZ();

    public static final int e_kGrave = ZFUIKeyCode.native_e_kGrave();
    private static native int native_e_kGrave();
    public static final int e_kMinus = ZFUIKeyCode.native_e_kMinus();
    private static native int native_e_kMinus();
    public static final int e_kEquals = ZFUIKeyCode.native_e_kEquals();
    private static native int native_e_kEquals();
    public static final int e_kBracketLeft = ZFUIKeyCode.native_e_kBracketLeft();
    private static native int native_e_kBracketLeft();
    public static final int e_kBracketRight = ZFUIKeyCode.native_e_kBracketRight();
    private static native int native_e_kBracketRight();
    public static final int e_kBackSlash = ZFUIKeyCode.native_e_kBackSlash();
    private static native int native_e_kBackSlash();
    public static final int e_kSemiColon = ZFUIKeyCode.native_e_kSemiColon();
    private static native int native_e_kSemiColon();
    public static final int e_kApostrophe = ZFUIKeyCode.native_e_kApostrophe();
    private static native int native_e_kApostrophe();
    public static final int e_kComma = ZFUIKeyCode.native_e_kComma();
    private static native int native_e_kComma();
    public static final int e_kPeriod = ZFUIKeyCode.native_e_kPeriod();
    private static native int native_e_kPeriod();
    public static final int e_kSlash = ZFUIKeyCode.native_e_kSlash();
    private static native int native_e_kSlash();

    public static final int e_kLeft = ZFUIKeyCode.native_e_kLeft();
    private static native int native_e_kLeft();
    public static final int e_kUp = ZFUIKeyCode.native_e_kUp();
    private static native int native_e_kUp();
    public static final int e_kRight = ZFUIKeyCode.native_e_kRight();
    private static native int native_e_kRight();
    public static final int e_kDown = ZFUIKeyCode.native_e_kDown();
    private static native int native_e_kDown();
    public static final int e_kHome = ZFUIKeyCode.native_e_kHome();
    private static native int native_e_kHome();
    public static final int e_kEnd = ZFUIKeyCode.native_e_kEnd();
    private static native int native_e_kEnd();
    public static final int e_kPageUp = ZFUIKeyCode.native_e_kPageUp();
    private static native int native_e_kPageUp();
    public static final int e_kPageDown = ZFUIKeyCode.native_e_kPageDown();
    private static native int native_e_kPageDown();
    public static final int e_kInsert = ZFUIKeyCode.native_e_kInsert();
    private static native int native_e_kInsert();
    public static final int e_kDelete = ZFUIKeyCode.native_e_kDelete();
    private static native int native_e_kDelete();
    public static final int e_kPrintScreen = ZFUIKeyCode.native_e_kPrintScreen();
    private static native int native_e_kPrintScreen();
    public static final int e_kScrollLock = ZFUIKeyCode.native_e_kScrollLock();
    private static native int native_e_kScrollLock();
    public static final int e_kPauseBreak = ZFUIKeyCode.native_e_kPauseBreak();
    private static native int native_e_kPauseBreak();

    public static final int e_kNum0 = ZFUIKeyCode.native_e_kNum0();
    private static native int native_e_kNum0();
    public static final int e_kNum1 = ZFUIKeyCode.native_e_kNum1();
    private static native int native_e_kNum1();
    public static final int e_kNum2 = ZFUIKeyCode.native_e_kNum2();
    private static native int native_e_kNum2();
    public static final int e_kNum3 = ZFUIKeyCode.native_e_kNum3();
    private static native int native_e_kNum3();
    public static final int e_kNum4 = ZFUIKeyCode.native_e_kNum4();
    private static native int native_e_kNum4();
    public static final int e_kNum5 = ZFUIKeyCode.native_e_kNum5();
    private static native int native_e_kNum5();
    public static final int e_kNum6 = ZFUIKeyCode.native_e_kNum6();
    private static native int native_e_kNum6();
    public static final int e_kNum7 = ZFUIKeyCode.native_e_kNum7();
    private static native int native_e_kNum7();
    public static final int e_kNum8 = ZFUIKeyCode.native_e_kNum8();
    private static native int native_e_kNum8();
    public static final int e_kNum9 = ZFUIKeyCode.native_e_kNum9();
    private static native int native_e_kNum9();
    public static final int e_kNumLock = ZFUIKeyCode.native_e_kNumLock();
    private static native int native_e_kNumLock();
    public static final int e_kNumAdd = ZFUIKeyCode.native_e_kNumAdd();
    private static native int native_e_kNumAdd();
    public static final int e_kNumMinus = ZFUIKeyCode.native_e_kNumMinus();
    private static native int native_e_kNumMinus();
    public static final int e_kNumMultiply = ZFUIKeyCode.native_e_kNumMultiply();
    private static native int native_e_kNumMultiply();
    public static final int e_kNumDivide = ZFUIKeyCode.native_e_kNumDivide();
    private static native int native_e_kNumDivide();
    public static final int e_kNumEnter = ZFUIKeyCode.native_e_kNumEnter();
    private static native int native_e_kNumEnter();
    public static final int e_kNumDot = ZFUIKeyCode.native_e_kNumDot();
    private static native int native_e_kNumDot();

    public static final int e_kMediaPlay = ZFUIKeyCode.native_e_kMediaPlay();
    private static native int native_e_kMediaPlay();
    public static final int e_kMediaPause = ZFUIKeyCode.native_e_kMediaPause();
    private static native int native_e_kMediaPause();
    public static final int e_kMediaPlayPause = ZFUIKeyCode.native_e_kMediaPlayPause();
    private static native int native_e_kMediaPlayPause();
    public static final int e_kMediaStop = ZFUIKeyCode.native_e_kMediaStop();
    private static native int native_e_kMediaStop();
    public static final int e_kMediaRecord = ZFUIKeyCode.native_e_kMediaRecord();
    private static native int native_e_kMediaRecord();
    public static final int e_kMediaPrev = ZFUIKeyCode.native_e_kMediaPrev();
    private static native int native_e_kMediaPrev();
    public static final int e_kMediaNext = ZFUIKeyCode.native_e_kMediaNext();
    private static native int native_e_kMediaNext();
    public static final int e_kMediaFastForward = ZFUIKeyCode.native_e_kMediaFastForward();
    private static native int native_e_kMediaFastForward();
    public static final int e_kMediaFastRewind = ZFUIKeyCode.native_e_kMediaFastRewind();
    private static native int native_e_kMediaFastRewind();

    public static final int e_kVolumeMute = ZFUIKeyCode.native_e_kVolumeMute();
    private static native int native_e_kVolumeMute();
    public static final int e_kVolumeUp = ZFUIKeyCode.native_e_kVolumeUp();
    private static native int native_e_kVolumeUp();
    public static final int e_kVolumeDown = ZFUIKeyCode.native_e_kVolumeDown();
    private static native int native_e_kVolumeDown();

    public static final int e_kPhoneCall = ZFUIKeyCode.native_e_kPhoneCall();
    private static native int native_e_kPhoneCall();
    public static final int e_kPhoneCallEnd = ZFUIKeyCode.native_e_kPhoneCallEnd();
    private static native int native_e_kPhoneCallEnd();
    public static final int e_kPhoneHome = ZFUIKeyCode.native_e_kPhoneHome();
    private static native int native_e_kPhoneHome();
    public static final int e_kPhoneMenu = ZFUIKeyCode.native_e_kPhoneMenu();
    private static native int native_e_kPhoneMenu();
    public static final int e_kPhoneBack = ZFUIKeyCode.native_e_kPhoneBack();
    private static native int native_e_kPhoneBack();
    public static final int e_kPhoneSearch = ZFUIKeyCode.native_e_kPhoneSearch();
    private static native int native_e_kPhoneSearch();
    public static final int e_kPhoneCamera = ZFUIKeyCode.native_e_kPhoneCamera();
    private static native int native_e_kPhoneCamera();

    public static final int EnumDefault = ZFUIKeyCode.native_EnumDefault();
    private native static int native_EnumDefault();
}

